In [2]:
import numpy as np

In [4]:
x=np.random.random((3,4))
x

array([[0.5641526 , 0.21491088, 0.62331725, 0.5968669 ],
       [0.01065086, 0.66823442, 0.21504777, 0.70377657],
       [0.217352  , 0.35609529, 0.03275348, 0.78567651]])

In [7]:
x.sum(axis=0)

array([0.79215545, 1.23924059, 0.8711185 , 2.08631997])

In [9]:
x.max(axis=1)

array([0.62331725, 0.70377657, 0.78567651])

In [12]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [13]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [18]:
c=np.arange(3)
d=np.array([[1,2],[3,4]])

print(c)
print(d)

[0 1 2]
[[1 2]
 [3 4]]


In [22]:
np.ones((2,3))




array([[1., 1., 1.],
       [1., 1., 1.]])