# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
arr1=np.arange(0,15,2)
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [3]:
#let us say we want to find the nearest value to 6
#use np.where() to return the index of the target value, minus from that index to find the nearest
np.where(arr1==6)[0]

array([3], dtype=int64)

In [4]:
arr1[(np.where(arr1==6)[0])-1]

array([4])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [5]:
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3).reshape(1,3)
it = np.nditer([arr1,arr2,None])#it is an object containing 3 arrays, arr1,arr2 and an empty one
for x,y,z in it: z[...] = x + y
print(it.operands[2])#accesses the empty array z where the result of the sum is stored

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [6]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [7]:
#np.add.at ufunc can be used to add numbers to values at specific indices in a vector
arr1=np.array([1,2,3,4,5])
arr2=np.array([0,1,2])
np.add.at(arr1,[arr2],1)
arr1

array([2, 3, 4, 4, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [47]:
X =([1,2,3,4,5,6])
Index_list= [1,3,9,3,4,1]
F = np.bincount(Index_list,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [8]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [11]:
arr1 = np.random.randint(0,10,(3,4,3,4))
arr1

array([[[[9, 2, 6, 4],
         [8, 4, 3, 1],
         [6, 6, 4, 2]],

        [[6, 2, 4, 0],
         [3, 4, 3, 6],
         [6, 0, 0, 4]],

        [[2, 7, 5, 2],
         [2, 8, 3, 3],
         [1, 5, 6, 5]],

        [[3, 6, 4, 6],
         [7, 8, 5, 8],
         [8, 1, 9, 6]]],


       [[[9, 9, 3, 2],
         [4, 4, 2, 0],
         [7, 6, 7, 5]],

        [[7, 9, 4, 3],
         [4, 7, 1, 4],
         [1, 9, 2, 4]],

        [[3, 6, 7, 0],
         [0, 8, 2, 4],
         [2, 0, 2, 9]],

        [[6, 4, 3, 0],
         [6, 9, 3, 9],
         [7, 8, 9, 9]]],


       [[[9, 5, 1, 1],
         [5, 2, 9, 3],
         [2, 9, 3, 9]],

        [[9, 4, 0, 2],
         [1, 0, 9, 4],
         [9, 8, 5, 6]],

        [[5, 5, 1, 3],
         [4, 6, 6, 0],
         [0, 8, 2, 3]],

        [[6, 5, 7, 5],
         [9, 4, 9, 5],
         [9, 5, 8, 2]]]])

In [21]:
#np.sum() allows us to sum along axis
#axes follow the rules of indexing first axis=0, 2nd=1,3...
sum = np.sum(arr1,axis=(2,3))
print(sum)


[[55 38 49 71]
 [58 55 43 73]
 [58 57 43 74]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [33]:
#create the 1D vector D
D = np.arange(0,10)
D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
S = np.random.randint(0,10,10)
S

array([0, 2, 7, 0, 1, 2, 1, 0, 6, 5])

In [35]:
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[3.33333333 5.         3.                nan        nan 9.
 8.         2.        ]


C:\Users\User\AppData\Local\Temp\ipykernel_4192\2016315713.py:3: RuntimeWarning: invalid value encountered in divide
  D_means = D_sums / D_counts


#### 69. How to get the diagonal of a dot product? (★★★)

In [38]:
arr1 = np.random.randint(0,10,(3,3))
arr2= np.random.randint(0,10,(3,3))
#product of arrays
arr3=np.dot(arr1,arr2)
np.diag(arr3)

array([38, 81, 14])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [53]:
#crate the vector
arr1= np.array([1,2,3,4,5])

In [54]:
#create a new array filled with zeros..
#length of the new array will be len of original array+len of original array-1 time the 3 zeros
arr2=np.zeros(len(arr1)+ (len(arr1)-1)*3)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
#fill the zeros array with values from arr1
arr2[::4]=arr1
arr2

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [61]:
arr1=np.full((5,5,3),1)
arr2=np.full((5,5),2)
#np.dot(arr1,arr2)
arr3=arr1*arr2[:,:,np.newaxis]
arr3

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

#### 72. How to swap two rows of an array? (★★★)

In [71]:
arr1=np.random.randint(0,10,(3,4))
arr1

array([[1, 7, 2, 5],
       [0, 8, 3, 6],
       [9, 6, 3, 2]])

In [72]:
np.roll(arr1,2,axis=0)

array([[0, 8, 3, 6],
       [9, 6, 3, 2],
       [1, 7, 2, 5]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [85]:
C = np.bincount([2,2,2,4,4,6,8,8,8,8,8])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)
print(np.bincount(A))

[0 0 3 0 2 0 1 0 5]
[2 2 2 4 4 6 8 8 8 8 8]
[0 0 3 0 2 0 1 0 5]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [92]:
#a sliding window is like a way of processing elements in an array sequentially,using a fixed window(like a frame)
#in which calculations are done
#stseps in this Q are...make a window, move it across the array, calculate average of element currently in window

#create a 1D array rep the sliding window
window=np.ones(window_size)/window_size
window_size=2
#print(window)
arr=np.arange(20)
averages=np.convolve(arr,window,mode='valid')
print(averages)




[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [94]:
Z = np.array([1, 2, 3,4,5,6,7])

# Create a 2D array by shifting the elements
result = np.column_stack((Z[:-2], Z[1:-1], Z[2:]))

print(result)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [98]:
arr1= np.random.randint(0,2,100)
np.logical_not(arr1, out=arr1)

arr1= np.random.uniform(-1.0,1.0,100)
np.negative(arr1, out=arr1)

array([-0.30832823, -0.51574121,  0.20612977, -0.73966318,  0.19537297,
       -0.05688844,  0.73874662, -0.67016766,  0.14833295, -0.35201301,
        0.00201108, -0.42158136, -0.16430265, -0.58238641,  0.62775921,
        0.43775645, -0.96258027,  0.63293512,  0.43299932,  0.35361403,
        0.76308092,  0.61203787,  0.52914386, -0.66029236, -0.6562827 ,
       -0.25724026,  0.28551587,  0.0959827 ,  0.49290706,  0.62062837,
       -0.19993329, -0.28199569,  0.69992815, -0.23264636, -0.49002936,
        0.16736494, -0.31978718, -0.44595375, -0.92531888,  0.57720111,
        0.02652981,  0.17023184, -0.76390489,  0.27068837,  0.65655816,
       -0.32618192,  0.33844799,  0.56482515, -0.2381632 , -0.5356841 ,
        0.28734979, -0.72986186,  0.06056801, -0.81711914,  0.17451924,
       -0.47231002, -0.37540843, -0.19894817, -0.92418963,  0.02468558,
       -0.81416054, -0.67581434, -0.66488019, -0.27012405,  0.05750485,
       -0.15176038, -0.14663863, -0.03741588,  0.85552779,  0.87

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [95]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.89322444  9.34194661  8.84520208  0.12737483  8.43046057  5.25487548
  9.06927217  0.97594721 10.18513052  0.91358368]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [96]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.31068931  9.25127673 11.70593124  0.07997318  7.59085905 12.88800323
  19.49266615  0.63270843  2.5594508   2.73315647]
 [ 5.42627975  4.62478637 13.00326136  4.09967539  3.00811637 10.27360011
  19.58060887  2.13428968  2.13375835  5.76937705]
 [ 5.33489074 16.16960136  3.59366939  3.52941025 15.04143603  2.63520582
   4.60368435 14.89260046  8.36416077 11.09046021]
 [ 1.1586095  17.55479856  0.11795175  0.57377462 16.24066391  7.51429019
   8.84581922 12.79330082 10.12029427  9.31440083]
 [ 8.59576021 13.92448659  4.62272453  6.78175775 12.89175266  0.39176677
   2.81419805 14.80653498  5.93602567 10.76960199]
 [ 4.81849379  8.72758709  7.86014525  3.3397382   7.25074068  8.35954166
  15.09222086  3.34460933  1.66557861  0.30243141]
 [ 2.38975272 18.66315477  2.93447074  4.05716944 17.18807856 11.70591081
  12.53987769 10.90796577 11.55009801  7.70474264]
 [ 4.7608191  13.49326729  1.03514437  3.08500953 12.21690337  5.23418279
   8.93869558 10.35344189  6.00148013  6.63908613]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [78]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [79]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [80]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [81]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.34061967, 0.22808013, 0.33317369, 0.04742923, 0.17567392,
        0.02994786, 0.11242512, 0.14641724, 0.28498634, 0.169676  ],
       [0.40908459, 0.27392448, 0.40014196, 0.05696255, 0.21098457,
        0.03596741, 0.13502269, 0.17584726, 0.3422689 , 0.20378106],
       [0.0731198 , 0.04896128, 0.07152139, 0.01018149, 0.03771139,
        0.00642882, 0.02413396, 0.03143095, 0.06117716, 0.03642384],
       [0.67297294, 0.45062504, 0.65826169, 0.0937074 , 0.34708446,
        0.05916892, 0.22212182, 0.28928112, 0.56305642, 0.33523418],
       [0.03236851, 0.02167407, 0.03166093, 0.00450712, 0.01669399,
        0.00284589, 0.01068357, 0.01391378, 0.02708177, 0.01612402],
       [0.65575862, 0.43909827, 0.64142367, 0.09131041, 0.3382062 ,
        0.05765541, 0.21644005, 0.28188145, 0.54865371, 0.32665906],
       [0.08351793, 0.0559239 , 0.08169222, 0.01162937, 0.04307421,
        0.00734304, 0.02756598, 0.03590064, 0.06987697, 0.04160355],
       [0.75656249, 0.50659689, 0.7400239

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [82]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23500562  0.1674311 ]
