# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [2]:
arr1=np.arange(0,15,2)
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [3]:
#let us say we want to find the nearest value to 6
#use np.where() to return the index of the target value, minus from that index to find the nearest
np.where(arr1==6)[0]

array([3], dtype=int64)

In [4]:
arr1[(np.where(arr1==6)[0])-1]

array([4])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [5]:
arr1 = np.arange(3).reshape(3,1)
arr2 = np.arange(3).reshape(1,3)
it = np.nditer([arr1,arr2,None])#it is an object containing 3 arrays, arr1,arr2 and an empty one
for x,y,z in it: z[...] = x + y
print(it.operands[2])#accesses the empty array z where the result of the sum is stored

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [6]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [7]:
#np.add.at ufunc can be used to add numbers to values at specific indices in a vector
arr1=np.array([1,2,3,4,5])
arr2=np.array([0,1,2])
np.add.at(arr1,[arr2],1)
arr1

array([2, 3, 4, 4, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [47]:
X =([1,2,3,4,5,6])
Index_list= [1,3,9,3,4,1]
F = np.bincount(Index_list,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [8]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [11]:
arr1 = np.random.randint(0,10,(3,4,3,4))
arr1

array([[[[9, 2, 6, 4],
         [8, 4, 3, 1],
         [6, 6, 4, 2]],

        [[6, 2, 4, 0],
         [3, 4, 3, 6],
         [6, 0, 0, 4]],

        [[2, 7, 5, 2],
         [2, 8, 3, 3],
         [1, 5, 6, 5]],

        [[3, 6, 4, 6],
         [7, 8, 5, 8],
         [8, 1, 9, 6]]],


       [[[9, 9, 3, 2],
         [4, 4, 2, 0],
         [7, 6, 7, 5]],

        [[7, 9, 4, 3],
         [4, 7, 1, 4],
         [1, 9, 2, 4]],

        [[3, 6, 7, 0],
         [0, 8, 2, 4],
         [2, 0, 2, 9]],

        [[6, 4, 3, 0],
         [6, 9, 3, 9],
         [7, 8, 9, 9]]],


       [[[9, 5, 1, 1],
         [5, 2, 9, 3],
         [2, 9, 3, 9]],

        [[9, 4, 0, 2],
         [1, 0, 9, 4],
         [9, 8, 5, 6]],

        [[5, 5, 1, 3],
         [4, 6, 6, 0],
         [0, 8, 2, 3]],

        [[6, 5, 7, 5],
         [9, 4, 9, 5],
         [9, 5, 8, 2]]]])

In [21]:
#np.sum() allows us to sum along axis
#axes follow the rules of indexing first axis=0, 
sum = np.sum(arr1,axis=(2,3))
print(sum)


[[55 38 49 71]
 [58 55 43 73]
 [58 57 43 74]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [13]:
#create the 1D vector D
D = np.random.uniform(0,1,10)
D

array([0.7324771 , 0.10903331, 0.9270837 , 0.65702476, 0.82832541,
       0.54673034, 0.32128715, 0.5012296 , 0.35587149, 0.87141631])

In [14]:
S = np.random.randint(0,10,10)
S

array([8, 9, 3, 8, 8, 9, 8, 6, 7, 8])

In [15]:
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[       nan        nan        nan 0.9270837         nan        nan
 0.5012296  0.35587149 0.68210615 0.32788183]


C:\Users\User\AppData\Local\Temp\ipykernel_4192\2016315713.py:3: RuntimeWarning: invalid value encountered in divide
  D_means = D_sums / D_counts


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)