# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2270588361616
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
# a null vector is where all the values are 0
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
#memory size=the number of bytes it occupies
print(array.itemsize)

8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
x=np.zeros(10, dtype=int)
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
y=np.arange(10,49,1)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
y[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
z=np.random.randint(0,8,(3,3))
print(z)

[[4 1 5]
 [2 6 5]
 [4 4 6]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
a=[1,2,0,0,4,0]
for index,ele in enumerate (a):
    if ele != 0:
        print(f'The non-zero element {ele}, is at index {index}')

The non-zero element 1, is at index 0
The non-zero element 2, is at index 1
The non-zero element 4, is at index 4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
w=np.eye(3,3)
print(w)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
u=np.random.random((3,3))
print(u)

[[0.33089855 0.94209812 0.15130219]
 [0.63620653 0.78383432 0.36707919]
 [0.21305848 0.29743769 0.97108613]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [37]:
m=np.random.random((10,10))
print(m)
print('########')
print(f'The maximum value is {np.max(m)}')
print(f'The minimum value is {np.min(m)}')

[[0.04036861 0.97886774 0.29220469 0.68101819 0.33851451 0.81128233
  0.25002915 0.67419216 0.77604693 0.22579534]
 [0.37370714 0.71163428 0.66489579 0.47474694 0.76225001 0.25427805
  0.07848993 0.17606379 0.69711174 0.52204433]
 [0.02920331 0.96828598 0.24718848 0.98188674 0.9065996  0.42816621
  0.10912012 0.34203532 0.37599661 0.55136154]
 [0.74971471 0.80042948 0.83688464 0.80739121 0.59961241 0.56361049
  0.9127378  0.29751565 0.44357685 0.95861544]
 [0.11379935 0.76976805 0.67215507 0.08115334 0.35976331 0.67434504
  0.45263256 0.09940651 0.47077681 0.75603223]
 [0.61395809 0.27298004 0.96615915 0.60875825 0.76072508 0.79949814
  0.91611981 0.69544449 0.89624054 0.73750568]
 [0.92969371 0.52540184 0.61420227 0.65307846 0.23962518 0.77082928
  0.2487978  0.27352936 0.25824928 0.7791395 ]
 [0.23709447 0.16567581 0.81616025 0.06738324 0.42340492 0.70331025
  0.46357085 0.56772065 0.33766276 0.83812639]
 [0.54486132 0.24656177 0.71928432 0.10031527 0.08587898 0.38695973
  0.65998549

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
array1=np.linspace(0.100,30)
print(array1)
print('########')
print(f'The mean values of the vector is {np.mean(array1)}')

[ 0.1         0.71020408  1.32040816  1.93061224  2.54081633  3.15102041
  3.76122449  4.37142857  4.98163265  5.59183673  6.20204082  6.8122449
  7.42244898  8.03265306  8.64285714  9.25306122  9.86326531 10.47346939
 11.08367347 11.69387755 12.30408163 12.91428571 13.5244898  14.13469388
 14.74489796 15.35510204 15.96530612 16.5755102  17.18571429 17.79591837
 18.40612245 19.01632653 19.62653061 20.23673469 20.84693878 21.45714286
 22.06734694 22.67755102 23.2877551  23.89795918 24.50816327 25.11836735
 25.72857143 26.33877551 26.94897959 27.55918367 28.16938776 28.77959184
 29.38979592 30.        ]
########
The mean values of the vector is 15.05


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
p=np.ones((4,4), dtype=int)
print(p)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [49]:
#change the 2 row first
p[1,1:3]=0
print(p)

[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]
 [1 1 1 1]]


In [50]:
#now change the 3rd row
p[2,1:3]=0
print(p)


[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
