# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [50]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [12]:
defaults = np.seterr(all="ignore")
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [13]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User\AppData\Local\Temp\ipykernel_8620\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [8]:
#use np.datetime64() + the np.timedelta64()
date_today=np.datetime64('today','D')
print(f'Todays date is {date_today}')
date_yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print(f'Yesterdays date was {date_yesterday}')
date_tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(f'Tomorrows date is {date_tomorrow}')

Todays date is 2024-02-20
Yesterdays date was 2024-02-19
Tomorrows date is 2024-02-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [11]:
Jul_16=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Jul_16)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [14]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [3]:
#create the random array with float values
arr1=np.random.random((1,5))
arr1

array([[0.20190553, 0.87575895, 0.22743077, 0.90730715, 0.69664479]])

In [4]:
#using ceil to get the integers-returns the smallest integer value which is greater than or equal to specified number
np.ceil(arr1)


array([[1., 1., 1., 1., 1.]])

In [5]:
#np,floor returns the largest integar value that is smaller that or equal to the specified number
np.floor(arr1)

array([[0., 0., 0., 0., 0.]])

In [8]:
#cast the type
print(arr1.astype(int))

[[0 0 0 0 0]]


In [10]:
print (np.trunc(arr1))

[[0. 0. 0. 0. 0.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
# Create a 5x5 matrix with row values ranging from 0 to 4
arr1= np.tile(np.arange(5), (5, 1))

print(arr1)



[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [25]:
# Define a generator function to generate 10 integers
def generator():
    for i in range(10):
        yield i

# Use the generator to build a NumPy array
arr1 = np.array(list(generator()))

print(arr1)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [33]:
arr1=np.linspace(0,1,12,endpoint=False)[1:]
arr1
#endpoint=false excludes the endpoint 1 from the array, th[1:] excludes the first ele=0

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333,
       0.91666667])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:
arr1=np.random.random(10)
arr1.sort()
print(arr1)

[0.05211425 0.15874738 0.19339696 0.25848231 0.67954932 0.72614856
 0.76418226 0.80940593 0.94259185 0.9690331 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
arr1=np.full((2,2),2)
arr1
np.add.reduce(arr1)

array([4, 4])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [48]:
#using the np.array_equal checks if 2 arrays have the same shape and elements
arr1=np.random.randint(0,10,(2,2))
arr2=np.arange(10)
print(arr1)
print(arr2)

[[1 6]
 [1 4]]
[0 1 2 3 4 5 6 7 8 9]


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
#use the flags writeable attribute
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr1.flags.writeable=False

In [45]:
#test if it worked
arr1[2]=3
arr1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [53]:
#create the cartesian array
cartesian=np.random.random((10,2))
cartesian
#first column is the x cordinate and second column is y

array([[0.09396114, 0.62995053],
       [0.8999965 , 0.08699885],
       [0.34970358, 0.15659803],
       [0.66292785, 0.34673862],
       [0.76222699, 0.58320971],
       [0.14538446, 0.25178929],
       [0.70424882, 0.41761449],
       [0.36320229, 0.45528863],
       [0.84127072, 0.73874465],
       [0.64933846, 0.83582071]])

In [56]:
#extracting each axis
x=cartesian[:,0]
y=cartesian[:,1]
#print(x)

[0.09396114 0.8999965  0.34970358 0.66292785 0.76222699 0.14538446
 0.70424882 0.36320229 0.84127072 0.64933846]


In [58]:
#Get r= √ ( x2 + y2 )
r = np.sqrt(x**2 + y**2)
#get θ = tan-1 ( y / x )
O=np.arctan2(y, x)


In [59]:
print(r)

[0.63691943 0.90419163 0.38316516 0.74813168 0.95975182 0.29074815
 0.8187602  0.58241192 1.11958924 1.05841234]


In [60]:
print(O)

[1.42273153 0.09636635 0.42102471 0.48191025 0.65311996 1.04715632
 0.53525123 0.89743451 0.72059972 0.91030826]


In [61]:
#now to make it into one array of r,O polar coordinates
polar=np.column_stack((r,O))
polar

array([[0.63691943, 1.42273153],
       [0.90419163, 0.09636635],
       [0.38316516, 0.42102471],
       [0.74813168, 0.48191025],
       [0.95975182, 0.65311996],
       [0.29074815, 1.04715632],
       [0.8187602 , 0.53525123],
       [0.58241192, 0.89743451],
       [1.11958924, 0.72059972],
       [1.05841234, 0.91030826]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [62]:
arr1= np.random.random(10)
arr1[arr1.argmax()] = 0
print(arr1)

[0.27336094 0.80486469 0.73498037 0.73379844 0.05095852 0.42123948
 0.81791024 0.41530423 0.04378364 0.        ]
